config/routes.rb
Community::Application.routes.draw do

  get 'sign_in' => 'sessions#new'
  get 'sign_out' => 'sessions#destroy'

  get 'sign_up' => 'users#new'

  resources :users

  root 'societies#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/society.rb
class Society < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/societies_controller.rb
class SocietiesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, notice: 'Thank you for registering. You can now login using your username and password.'
    else
      render :new
    end
  end

  private

  def user_params
    params.required(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/societies_helper.rb
module SocietiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_default_nav.html.erb
<%= nav_bar brand: 'MINECRAFT SOCIETIES', responsive: true do %>
    <%= menu_group pull: :right do %>
        <%= drop_down 'Account' do %>
            <%= menu_item 'Sign Up', sign_up_path %>
            <%= menu_item 'Sign In', sign_in_path %>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  <meta name="description" content="Minecraft Societies is a website for the communities of Anthemion and Meerkats on Minecraft." />
  <title>Minecraft Societies</title>
  <link data-turbolinks-track="true" href="http://fonts.googleapis.com/css?family=PT+Sans|Montserrat:400,700" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= render "application/default_nav" %>

    <%= bootstrap_flash %>

    <%= yield %>
  </div>

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/societies/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 well"></div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="page-header">
      <h1>Sign Up</h1>
    </div>
    <%= form_for @user, html: { role: 'form' } do |f| %>
    <div class="row">
      <div class="col-md-6">
        <%= f.label :username, class: 'sr-only' %>
        <%= f.text_field :username, class: 'form-control', placeholder: 'Username' %>
      </div>
      <div class="col-md-6">
        <%= f.label :email, class: 'sr-only' %>
        <%= f.text_field :email, class: 'form-control', placeholder: 'E-Mail' %> <br/>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= f.label :password, class: 'sr-only' %>
        <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
      </div>
      <div class="col-md-6">
        <%= f.label :password_confirmation, class: 'sr-only' %>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password Confirmation' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 col-md-offset-8">
        <%= f.submit 'Sign Up', class: 'btn btn-success' %>
        <%= link_to 'Cancel', root_path %>
      </div>
    </div>
    <% end %>
  </div>
</div>